version: 2

sources:
  - name: airbnb  #just for reference, a name has been given, it can be different wrt to the source database
    database: airbnb #source database name present in snf
    schema: raw #source schema name present in snf
    tables:
      - name: raw_hosts #remember this name should be used in sources sql file to call / use the source table
        identifier: raw_hosts #give the source table name which is present in snf

      - name: raw_listings    #remember this name should be used in sources sql file to call / use the source table
        identifier: raw_listings #give the source table name which is present in snf
      
      - name: raw_reviews
      - identifier: raw_reviews 